#version 460
layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba16f,set = 0, binding = 0) uniform image2D data;

void main() {
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(data);

	
	if(texelCoord.x < size.x && texelCoord.y < size.y)
	{
		vec3 normal = vec3(0);

		float height = sin(float(texelCoord.x)/10) + cos(float(texelCoord.y)/10);

		imageStore(data, texelCoord, vec4(normal,height));
	}
}